# Loki Log Aggregation Values
loki:
  auth_enabled: false
  
  commonConfig:
    replication_factor: 1
  
  storage:
    type: filesystem
  
  schemaConfig:
    configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

singleBinary:
  replicas: 1
  
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
  
  persistence:
    enabled: true
    size: 10Gi

# Disable other components for single binary deployment
ingester:
  enabled: false
distributor:
  enabled: false
querier:
  enabled: false
queryFrontend:
  enabled: false
queryScheduler:
  enabled: false
compactor:
  enabled: false
indexGateway:
  enabled: false
ruler:
  enabled: false

test:
  enabled: false

monitoring:
  serviceMonitor:
    enabled: true