apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-config
  namespace: bookmarks
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: prometheus-secret
    creationPolicy: Owner
  data:
  - secretKey: adminPassword
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: secret/data/homelab/prometheus
      metadataPolicy: None
      property: adminPassword